/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Ionic Sample API
 * Spec-First learning project. Single source of truth for FE (Orval) and BE (Spring Boot).
 * OpenAPI spec version: 1.0.0
 */

export interface Item {
  id: number;
  name: string;
  price: number;
}
