/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Ionic Sample API
 * Spec-First learning project. Single source of truth for FE (Orval) and BE (Spring Boot).
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary List all items
 */
export const ListItemsResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "price": zod.number()
})
export const ListItemsResponse = zod.array(ListItemsResponseItem)

/**
 * @summary Create a new item
 */
export const CreateItemBody = zod.object({
  "name": zod.string(),
  "price": zod.number()
})

/**
 * @summary Get one item by id
 */
export const GetItemParams = zod.object({
  "id": zod.number()
})

export const GetItemResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "price": zod.number()
})

/**
 * @summary Delete one item
 */
export const DeleteItemParams = zod.object({
  "id": zod.number()
})

