/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Ionic Sample API
 * Spec-First learning project. Single source of truth for FE (Orval) and BE (Spring Boot).
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  Item
} from '../models';


export const getListItemsResponseMock = (): Item[] => ([{"id":1,"name":"ペン","price":200},{"id":2,"name":"ノート","price":800}])

export const getCreateItemResponseMock = (overrideResponse: Partial<Extract<Item, object>> = {}): Item => ({id: faker.number.int(), name: faker.string.alpha({length: {min: 10, max: 20}}), price: faker.number.int(), ...overrideResponse})

export const getGetItemResponseMock = (): Item => ({"id":1,"name":"ペン","price":200})


export const getListItemsMockHandler = (overrideResponse?: Item[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Item[]> | Item[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/items', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListItemsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateItemMockHandler = (overrideResponse?: Item | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Item> | Item), options?: RequestHandlerOptions) => {
  return http.post('*/api/items', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateItemResponseMock(),
      { status: 201
      })
  }, options)
}

export const getGetItemMockHandler = (overrideResponse?: Item | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Item> | Item), options?: RequestHandlerOptions) => {
  return http.get('*/api/items/:id', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetItemResponseMock(),
      { status: 200
      })
  }, options)
}

export const getDeleteItemMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/items/:id', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}
export const getDefaultMock = () => [
  getListItemsMockHandler(),
  getCreateItemMockHandler(),
  getGetItemMockHandler(),
  getDeleteItemMockHandler()]
