/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Ionic Sample API
 * Spec-First learning project. Single source of truth for FE (Orval) and BE (Spring Boot).
 * OpenAPI spec version: 1.0.0
 */
import type {
  Item,
  ItemCreate
} from '../models';

import { request } from '.././axios';



  /**
 * @summary List all items
 */
export const listItems = (

 ) => {
      return request<Item[]>(
      {url: `/api/items`, method: 'GET'
    },
      );
    }
  /**
 * @summary Create a new item
 */
export const createItem = (
    itemCreate: ItemCreate,
 ) => {
      return request<Item>(
      {url: `/api/items`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: itemCreate
    },
      );
    }
  /**
 * @summary Get one item by id
 */
export const getItem = (
    id: number,
 ) => {
      return request<Item>(
      {url: `/api/items/${id}`, method: 'GET'
    },
      );
    }
  /**
 * @summary Delete one item
 */
export const deleteItem = (
    id: number,
 ) => {
      return request<void>(
      {url: `/api/items/${id}`, method: 'DELETE'
    },
      );
    }
